// stencil/src/components/todo-input/todo-input.tsx
import { Component, State, Event, EventEmitter } from '@stencil/core';

@Component({
  tag: 'todo-input',
  styleUrl: 'todo-input.scss',
  shadow: true,
})
export class TodoInput {
  @Event() onTodoInputSubmit: EventEmitter;
  @State() value: string;

  handleOnSubmit = (e) => {
    e.preventDefault();
    if (!this.value) return;
    this.onTodoInputSubmit.emit(this.value);
    this.value = '';
  }

  handleInputChange = (event) => this.value = event.target.value;

  render() {
    return (
      <form onSubmit={this.handleOnSubmit}>
        <input
          value={this.value}
          type="text"
          placeholder="What needs to be done?"
          onInput={this.handleInputChange}
        />
      </form>
    );
  }
}

// non-web-components-refs/react/src/components/todo-input/todo-input.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import './todo-input.css';

class MyTodo extends Component {
  state = { value: '' };

  static propTypes = {
    onTodoInputSubmit: PropTypes.func.isRequired,
  };

  handleOnSubmit = (e) => {
    e.preventDefault();
    if (!this.state.value) return;
    this.props.onTodoInputSubmit(this.state.value);
    this.setState({ value: '' });
  }

  handleInputChange = (event) => this.setState({ value: event.target.value });

  render() {
    const { checked, text } = this.props;
    return (
      <form onSubmit={this.handleOnSubmit}>
        <input
          value={this.state.value}
          type="text"
          placeholder="What needs to be done?"
          onInput={this.handleInputChange}
        />
      </form>
    );
  }
}

export default MyTodo;
