// stencil/src/components/my-todo/my-todo.tsx
import { Component, State, Listen } from '@stencil/core';

interface TodoItem {
  text: string;
  checked: boolean;
}

@Component({
  tag: 'my-todo',
  styleUrl: 'my-todo.scss',
  shadow: true,
})
export class MyTodo {
  @State() list: TodoItem[] = [
    { text: 'my initial todo', checked: false },
    { text: 'Learn about Web Components', checked: true }
  ];

  @Listen('onTodoInputSubmit')
  todoInputSubmiHandler(e: CustomEvent) {
    this.list = [...this.list, { text: e.detail, checked: false, }];
  }

  @Listen('onTodoItemChecked')
  todoItemCheckedHandler(e: CustomEvent) {
    const list = [...this.list];
    const item = list[e.detail];
    list[e.detail] = Object.assign({}, item, { checked: !item.checked });
    this.list = list;
  }

  @Listen('onTodoItemRemove')
  todoItemRemoveHandler(e: CustomEvent) {
    this.list = [...this.list.slice(0, e.detail), ...this.list.slice(e.detail + 1)];
  }

  render() {
    return (
      <div>
        <h1>Todos Stencil</h1>
        <section>
          <todo-input></todo-input>
          <ul id="list-container">
            {this.list.map((item, index) => (
              <todo-item
                checked={item.checked}
                text={item.text}
                index={index}
              />
            ))}
          </ul>
        </section>
      </div>
    );
  }
}

// non-web-components-refs/react/src/components/my-todo/my-todo.js
import React, { Component } from 'react';

import './my-todo.css';
import TodoInput from '../todo-input/todo-input';
import TodoItem from '../todo-item/todo-item';

class MyTodo extends Component {
  state = {
    list: [
      { text: 'my initial todo', checked: false },
      { text: 'Learn about Web Components', checked: true }
    ],
  }

  handleOnTodoInputSubmit = (text) => {
    this.setState({ list: [...this.state.list, { text, checked: false, }] });
  }

  handleOnTodoItemChecked = (index) => {
    const { list } = this.state;
    const newList = [...list];
    const item = newList[index];
    newList[index] = Object.assign({}, item, { checked: !item.checked });
    this.setState({ list: newList });
  }

  handleOnTodoItemRemove = (index) => {
    const { list } = this.state;
    this.setState({ list: [...list.slice(0, index), ...list.slice(index + 1)] });
  }

  render() {
    return (
      <div className="MyTodo">
        <h1>Todos React</h1>
        <section>
          <TodoInput onTodoInputSubmit={this.handleOnTodoInputSubmit} />
          <ul id="list-container">
            {this.state.list.map((item, index) => (
              <TodoItem
                key={index}
                checked={item.checked}
                text={item.text}
                index={index}
                onTodoItemRemove={this.handleOnTodoItemRemove}
                onTodoItemChecked={this.handleOnTodoItemChecked}
              />
            ))}
          </ul>
        </section>
      </div>
    );
  }
}

export default MyTodo;
