// stencil/src/components/todo-item/todo-item.tsx

import { Component, Prop, Event, EventEmitter } from '@stencil/core';

@Component({
  tag: 'todo-item',
  styleUrl: 'todo-item.scss',
  shadow: true,
})
export class TodoItem {
  @Prop() checked: boolean;
  @Prop() text: string;
  @Prop() index: number;
  @Event() onTodoItemChecked: EventEmitter;
  @Event() onTodoItemRemove: EventEmitter;

  handleOnRemove = () => this.onTodoItemRemove.emit(this.index);
  handleOnChecked = () => this.onTodoItemChecked.emit(this.index);

  render() {
    return (
      <li class={this.checked ? 'completed' : ''}>
        <input type="checkbox" checked={this.checked} onChange={this.handleOnChecked} />
        <label>{this.text}</label>
        <button onClick={this.handleOnRemove}>x</button>
      </li>
    );
  }
}

// non-web-components-refs/react/src/components/todo-item/todo-item.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import './todo-item.css';

class MyTodo extends Component {
  static propTypes = {
    checked: PropTypes.bool.isRequired,
    text: PropTypes.string.isRequired,
    index: PropTypes.number.isRequired,
    onTodoItemRemove: PropTypes.func.isRequired,
    onTodoItemChecked: PropTypes.func.isRequired,
  };

  handleOnRemove = () => this.props.onTodoItemRemove(this.props.index);
  handleOnChecked = () => this.props.onTodoItemChecked(this.props.index);

  render() {
    const { checked, text } = this.props;
    return (
      <li className={checked ? 'completed' : ''}>
        <input type="checkbox" checked={checked} onChange={this.handleOnChecked} />
        <label>{text}</label>
        <button onClick={this.handleOnRemove}>x</button>
      </li>
    );
  }
}

export default MyTodo;
