// solid/src/TodoInput.jsx
import { customElement } from 'solid-element';
import { createState } from 'solid-js';

import style from './TodoInput.css';

const TodoInput = (props, { element }) => {
  const [state, setState] = createState({ value: '' }),
    handleSubmit = e => {
      e.preventDefault();
      if (!state.value) return;
      props.createTodo(state.value);
      setState({ value: '' });
    };

  return (<>
    <style>{ style }</style>
    <form onSubmit={ handleSubmit }>
      <input
        value={( state.value )}
        type="text"
        placeholder="What needs to be done?"
        onInput={({ target: { value } }) => setState({ value })}
      />
    </form>
  </>);
}

customElement('todo-input', { createTodo: null }, TodoInput);

// stencil-0.11/src/components/todo-input/todo-input.tsx
import { Component, State, Event, EventEmitter } from '@stencil/core';

@Component({
  tag: 'todo-input',
  styleUrl: 'todo-input.css',
  // shadow: true,
})
export class TodoInput {
  @Event() onTodoInputSubmit: EventEmitter;
  @State() value: string;

  handleOnSubmit = (e) => {
    e.preventDefault();
    if (!this.value) return;
    this.onTodoInputSubmit.emit(this.value);
    this.value = '';
  }

  handleInputChange = (event) => this.value = event.target.value;

  render() {
    return (
      <form onSubmit={this.handleOnSubmit}>
        <input
          value={this.value}
          type="text"
          placeholder="What needs to be done?"
          onInput={this.handleInputChange}
        />
      </form>
    );
  }
}
